// ============================================================================
// Canary Engine
// https://github.com/HylightGames/canary
//
// Copyright (c) 2026-present Canary Engine contributors
//
// Licensed under the MIT License.
// See LICENSE in the project root for details.
// ============================================================================

//! WAV + Ogg Vorbis sound loading: file bytes become a validated [`Sound`].
//!
//! The two formats this release reads are WAV (decoded by the pure-Rust
//! `hound` crate) and Ogg Vorbis (decoded by the pure-Rust `lewton`
//! crate): together they cover the v0.0.12 audio milestone's "real sound
//! assets" bar — lossless authoring interchange plus compressed shipping
//! content — without the format-breadth attack surface (and the MPL-2.0
//! license) a full Symphonia dependency would drag in. See `Cargo.toml`
//! for the license rationale. As with the mesh and texture loaders,
//! third-party types never escape this module: the public surface is
//! [`Sound`] (plain integers plus one float vector) and [`load_sound`] /
//! [`load_sound_with_budget`] (a path in, validated values out).
//!
//! Fixture provenance: `tests/fixtures/tone-mono-8k.wav` (mono 16-bit PCM
//! with hand-picked sample values) is byte-generated by a dependency-free
//! Python script and `tests/fixtures/tone-stereo-8k.ogg` (stereo Vorbis)
//! is encoded from a generated tone with `ffmpeg`; see
//! `tests/fixtures/README.md` for the exact commands so both can be
//! regenerated. Tests assert loader *output values* (sample rate,
//! channels, decoded samples) against checked-in expectations — exact
//! bits for lossless WAV, documented epsilon windows for lossy Vorbis.
//!
//! A `Sound` is deliberately playback-agnostic: no audio crate exists
//! yet, so this type is shaped so a future `canary-audio` crate can
//! consume `AssetHandle<Sound>` directly (interleaved `f32` PCM is the
//! mixing-friendly layout).

use std::io::Cursor;
use std::path::Path;

use crate::io::{read_file_with_budget, resolve_in_root, MAX_ASSET_FILE_BYTES};
use crate::AssetError;

/// Default ceiling for the decoded size of one sound, in sample values
/// (frames times channels — the length of [`Sound::samples`]).
///
/// Sixteen megasamples is ~64 MiB as `f32`, matching the texture
/// loader's [`crate::DEFAULT_MAX_TEXTURE_BYTES`] byte ceiling so the two
/// decode budgets encode one shared opinion about "too big" rather than
/// two; as decoded stereo at 48 kHz it is roughly three minutes of
/// audio, orders of magnitude past this release's sub-second fixtures.
/// The value is **provisional** — a DoS bound chosen before any real
/// content exists to calibrate against, exactly like the mesh and
/// texture budgets — and callers with measured needs pass their own
/// ceiling to [`load_sound_with_budget`] instead.
pub const DEFAULT_MAX_SOUND_SAMPLES: u64 = 1 << 24;

/// Sound loaded from a WAV or Ogg Vorbis file: interleaved `f32` PCM
/// plus the rate and channel count that give the samples meaning.
///
/// `samples` holds `frame_count * channel_count` values in
/// frame-interleaved order — `[L0, R0, L1, R1, ...]` for stereo, one
/// value per frame for mono — normalized to `[-1, 1]`: integer sources
/// divide by their full-scale divisor (8-bit by 128, 16-bit by 32768,
/// 24-bit by 8388608, 32-bit by 2147483648), 32-bit float WAV passes
/// through byte-identical, and Vorbis packets arrive from `lewton` as
/// `i16` and divide by 32768. One in-memory layout at load time, so no
/// consumer ever branches on "which container and bit depth was this?".
///
/// Only mono (1 channel) and stereo (2 channels) are accepted: the
/// future mixer this feeds has no surround-panning story yet, so a
/// 5.1 file is an explicit [`AssetError::UnsupportedFeature`] rather
/// than a silent downmix that invents mixing policy at the loader.
#[derive(Debug, Clone, PartialEq)]
pub struct Sound {
    sample_rate: u32,
    channels: u16,
    samples: Vec<f32>,
}

impl Sound {
    /// Samples per second (e.g. 8000, 44100, 48000).
    ///
    /// Nonzero by construction: [`load_sound_with_budget`] rejects a
    /// zero rate rather than storing a value every duration computation
    /// would divide by.
    pub fn sample_rate(&self) -> u32 {
        self.sample_rate
    }

    /// Channel count: always 1 (mono) or 2 (stereo) for successfully
    /// loaded sounds.
    pub fn channel_count(&self) -> u16 {
        self.channels
    }

    /// Interleaved `f32` PCM samples in `[-1, 1]`, `frame_count *
    /// channel_count` values in frame-interleaved order.
    ///
    /// The length invariant is established at load time (see
    /// [`load_sound_with_budget`]), so consumers may chunk this into
    /// frames of [`Sound::channel_count`] without re-validating.
    pub fn samples(&self) -> &[f32] {
        &self.samples
    }

    /// The number of audio frames (length of [`Sound::samples`] divided
    /// by [`Sound::channel_count`]).
    ///
    /// Nonzero by construction: empty streams are rejected at load
    /// time, so downstream code may rely on this being populated
    /// without re-checking.
    pub fn frame_count(&self) -> usize {
        self.samples.len() / usize::from(self.channels)
    }
}

/// Loads the WAV or Ogg Vorbis file at `path` as a [`Sound`],
/// enforcing [`DEFAULT_MAX_SOUND_SAMPLES`].
///
/// This is the entry point most callers want: one path in, one validated
/// sound out, with the workspace-standard budget. Callers that have
/// measured their content (or tests proving the over-budget path) use
/// [`load_sound_with_budget`] with an explicit ceiling instead.
///
/// Container dispatch sniffs magic bytes, not the file extension: files
/// starting with `RIFF....WAVE` decode as WAV, files starting with
/// `OggS` decode as Ogg Vorbis, and anything else fails as
/// [`AssetError::InvalidFormat`] — a misnamed file still loads when its
/// bytes are honest.
///
/// See [`load_sound_with_budget`] for the conversion contract and the
/// full failure taxonomy.
pub fn load_sound(path: &Path) -> Result<Sound, AssetError> {
    load_sound_with_budget(path, DEFAULT_MAX_SOUND_SAMPLES)
}

/// Loads the WAV or Ogg Vorbis file at root-relative `candidate` as a
/// [`Sound`], enforcing [`DEFAULT_MAX_SOUND_SAMPLES`] and refusing
/// anything that escapes `root`.
///
/// The confined twin of [`load_sound`] for the future asset manager:
/// the candidate is resolved with [`crate::resolve_in_root`] first (a
/// `..` escape, an absolute path, or a symlink-out fails as
/// [`AssetError::OutsideRoot`] before a byte is read), then decoded
/// exactly like [`load_sound_with_budget`] — same conversion contract,
/// same budgets, same values. See
/// [`load_sound_with_budget_within_root`] for an explicit ceiling.
pub fn load_sound_within_root(root: &Path, candidate: &Path) -> Result<Sound, AssetError> {
    load_sound_with_budget_within_root(root, candidate, DEFAULT_MAX_SOUND_SAMPLES)
}

/// Loads the WAV or Ogg Vorbis file at `path` as a [`Sound`], refusing
/// decodes whose output would exceed `max_decode_samples` sample values
/// (frames times channels).
///
/// Conversion contract — every supported input normalizes to
/// frame-interleaved `f32` PCM in `[-1, 1]` (see [`Sound`]): WAV
/// integer bit depths 8/16/24/32 divide by their full-scale divisor,
/// 32-bit float WAV passes through, and Vorbis `i16` packets divide by
/// 32768. WAV files with any other bit depth or float width, and files
/// with more than two channels in either container, fail as
/// [`AssetError::UnsupportedFeature`] (the file is fine; this minimal
/// loader declines it).
///
/// Budget contract — refused *before* allocating, in sample values
/// throughout (which is what [`AssetError::OverBudget`] reports): the
/// WAV header's claimed sample count is checked first (a tiny file
/// claiming gigasamples fails here, with both numbers attached), and
/// the Vorbis packet loop carries a running total that refuses the
/// moment it passes the ceiling, so a hostile stream can overrun by at
/// most one packet. Decoded buffers grow through `try_reserve`, so even
/// a caller-approved huge budget surfaces allocation failure as `Err`,
/// never as an allocator abort.
///
/// Failure taxonomy (all variants carry `path`):
/// - Missing/unreadable file → [`AssetError::Io`].
/// - File past [`MAX_ASSET_FILE_BYTES`] → [`AssetError::OverBudget`],
///   refused before its bytes are allocated — ahead of every
///   decode-budget gate below, which only fires once bytes exist.
/// - Unrecognized magic, corrupt headers, truncated data, a zero sample
///   rate, an empty stream, decoder output that disagrees with the
///   header → [`AssetError::InvalidFormat`].
/// - Claimed or actual sample count past `max_decode_samples` →
///   [`AssetError::OverBudget`].
/// - Channel counts past stereo, WAV bit depths outside 8/16/24/32-bit
///   integer and 32-bit float → [`AssetError::UnsupportedFeature`].
///
/// Synchronous and panic-free over file inputs, like `crate::mesh` and
/// `crate::texture`: malformed files produce `Err`, and there is no
/// `async` API (ADR 0018).
pub fn load_sound_with_budget(path: &Path, max_decode_samples: u64) -> Result<Sound, AssetError> {
    let bytes = read_file_with_budget(path, MAX_ASSET_FILE_BYTES)?;
    load_sound_from_bytes(path, &bytes, max_decode_samples)
}

/// Loads the WAV or Ogg Vorbis file at root-relative `candidate` as a
/// [`Sound`], refusing decodes whose output would exceed
/// `max_decode_samples` and refusing anything that escapes `root`.
///
/// The confined twin of [`load_sound_with_budget`]: the candidate is
/// resolved with [`crate::resolve_in_root`] first (a `..` escape, an
/// absolute path, or a symlink-out fails as
/// [`AssetError::OutsideRoot`] before a byte is read), then decoded
/// exactly like [`load_sound_with_budget`] — same conversion contract,
/// same budgets, same values. A valid in-root file decodes
/// value-identical to the direct entry point.
pub fn load_sound_with_budget_within_root(
    root: &Path,
    candidate: &Path,
    max_decode_samples: u64,
) -> Result<Sound, AssetError> {
    let resolved = resolve_in_root(root, candidate)?;
    load_sound_with_budget(&resolved, max_decode_samples)
}

/// Dispatches in-memory `bytes` (attributed to `path` in errors) to the
/// WAV or Ogg Vorbis decoder by magic bytes.
///
/// Split from [`load_sound_with_budget`] so tests can feed in-memory
/// mutations of fixture bytes (truncated, magic-swapped,
/// header-patched) without touching disk, while every error still names
/// the originating file. Private: callers outside this crate load from
/// paths, keeping "which file" unambiguous.
fn load_sound_from_bytes(
    path: &Path,
    bytes: &[u8],
    max_decode_samples: u64,
) -> Result<Sound, AssetError> {
    // Both magics need at least 12 bytes (`RIFF` + size + `WAVE` for
    // WAV, the `OggS` capture pattern plus header fields for Ogg), so
    // anything shorter cannot be either format — rejected before either
    // decoder sees it.
    if bytes.len() < 12 {
        return Err(AssetError::invalid_format(
            path,
            "file is too short to hold a WAV or Ogg Vorbis header",
        ));
    }
    if bytes.starts_with(b"RIFF") && bytes[8..12] == *b"WAVE" {
        decode_wav(path, bytes, max_decode_samples)
    } else if bytes.starts_with(b"OggS") {
        decode_ogg(path, bytes, max_decode_samples)
    } else {
        Err(AssetError::invalid_format(
            path,
            "unrecognized audio magic: expected RIFF/WAVE for WAV or OggS for Ogg Vorbis",
        ))
    }
}

/// Decodes WAV `bytes` into a [`Sound`] under the sample budget.
///
/// The header's claimed sample count (`WavReader::len`, frames times
/// channels straight from the data-chunk size) is the earliest place a
/// lying file is refused — before any sample allocation — and the
/// decoded collect is cross-checked against that claim immediately
/// after, so a truncated data chunk surfaces as
/// [`AssetError::InvalidFormat` rather than a short sound. The
/// `hound` error type stays inside this function: it never appears in
/// a public signature.
fn decode_wav(path: &Path, bytes: &[u8], max_decode_samples: u64) -> Result<Sound, AssetError> {
    let invalid = |reason: String| AssetError::invalid_format(path, reason);

    let mut reader = hound::WavReader::new(Cursor::new(bytes))
        .map_err(|source| invalid(format!("not a parseable WAV file: {source}")))?;
    let spec = reader.spec();

    check_channels(path, spec.channels)?;
    if spec.sample_rate == 0 {
        return Err(invalid("WAV sample rate is zero".to_string()));
    }
    let full_scale = check_wav_sample_format(path, &spec)?;

    // Earliest refusal point for a lying header: `len()` derives from
    // the data-chunk size without touching sample bytes.
    let claimed = u64::from(reader.len());
    check_samples_budget(path, max_decode_samples, claimed)?;
    if claimed == 0 {
        return Err(invalid("WAV file contains no samples".to_string()));
    }

    // `try_reserve`, not `vec![0.0; n]`: a huge (caller-approved)
    // budget must surface as `Err` on allocation failure, never as an
    // allocator abort, keeping the loader's total-over-inputs promise.
    // `claimed` fits `u32` (it came from one), so this narrowing cannot
    // fail — but it still goes through `try_from`, never `as`.
    let capacity = usize::try_from(claimed)
        .map_err(|_| AssetError::over_budget(path, max_decode_samples, claimed))?;
    let mut samples = Vec::new();
    samples
        .try_reserve(capacity)
        .map_err(|_| AssetError::over_budget(path, max_decode_samples, claimed))?;

    match spec.sample_format {
        hound::SampleFormat::Int => {
            for sample in reader.samples::<i32>() {
                let value = sample
                    .map_err(|source| invalid(format!("WAV data chunk is truncated: {source}")))?;
                samples.push(normalize_int_sample(value, full_scale));
            }
        }
        hound::SampleFormat::Float => {
            for sample in reader.samples::<f32>() {
                let value = sample
                    .map_err(|source| invalid(format!("WAV data chunk is truncated: {source}")))?;
                samples.push(value);
            }
        }
    }

    let decoded = u64::try_from(samples.len())
        .map_err(|_| AssetError::over_budget(path, max_decode_samples, u64::MAX))?;
    if decoded != claimed {
        return Err(invalid(format!(
            "WAV data holds {decoded} samples but the header claims {claimed}"
        )));
    }

    Ok(Sound {
        sample_rate: spec.sample_rate,
        channels: spec.channels,
        samples,
    })
}

/// Decodes Ogg Vorbis `bytes` into a [`Sound`] under the sample budget.
///
/// Vorbis headers carry no total sample count the loader can trust, so
/// the budget rides along as a running total across decoded packets:
/// the check fires the moment the total passes the ceiling, bounding a
/// hostile stream's overrun to a single packet. Packets arrive from
/// `lewton` as interleaved `i16` (`read_dec_packet_itl`), already in
/// the [`Sound`] layout — this function only normalizes and enforces.
/// The `lewton` error type stays inside this function: it never appears
/// in a public signature.
fn decode_ogg(path: &Path, bytes: &[u8], max_decode_samples: u64) -> Result<Sound, AssetError> {
    let invalid = |reason: String| AssetError::invalid_format(path, reason);

    let mut reader = lewton::inside_ogg::OggStreamReader::new(Cursor::new(bytes))
        .map_err(|source| invalid(format!("not a parseable Ogg Vorbis stream: {source}")))?;
    // `audio_channels` is a `u8` in this lewton version: widen
    // infallibly at the boundary so the rest of the loader speaks
    // the crate's `u16` channel type throughout.
    let channels = u16::from(reader.ident_hdr.audio_channels);
    let sample_rate = reader.ident_hdr.audio_sample_rate;
    check_channels(path, channels)?;
    if sample_rate == 0 {
        return Err(invalid("Ogg Vorbis sample rate is zero".to_string()));
    }

    let mut samples = Vec::new();
    let mut total: u64 = 0;
    while let Some(packet) = reader
        .read_dec_packet_itl()
        .map_err(|source| invalid(format!("Ogg Vorbis packet failed to decode: {source}")))?
    {
        let count = u64::try_from(packet.len())
            .map_err(|_| AssetError::over_budget(path, max_decode_samples, u64::MAX))?;
        total = total
            .checked_add(count)
            .ok_or_else(|| AssetError::over_budget(path, max_decode_samples, u64::MAX))?;
        if total > max_decode_samples {
            return Err(AssetError::over_budget(path, max_decode_samples, total));
        }
        samples
            .try_reserve(packet.len())
            .map_err(|_| AssetError::over_budget(path, max_decode_samples, total))?;
        samples.extend(packet.iter().map(|sample| f32::from(*sample) / 32768.0));
    }

    if samples.is_empty() {
        return Err(invalid(
            "Ogg Vorbis stream contains no audio packets".to_string(),
        ));
    }
    // `read_dec_packet_itl` interleaves whole frames, so a remainder
    // means the stream's own channel framing broke — refused rather
    // than served as a ragged tail.
    if samples.len() % usize::from(channels) != 0 {
        return Err(invalid(format!(
            "Ogg Vorbis stream holds {} samples for {channels} channels, not a whole number of frames",
            samples.len()
        )));
    }

    Ok(Sound {
        sample_rate,
        channels,
        samples,
    })
}

/// Rejects channel counts outside mono/stereo.
///
/// Shared by the WAV and Ogg paths so the two containers cannot drift
/// into different taxonomies for the same condition: multichannel is a
/// loader-narrowness failure ([`AssetError::UnsupportedFeature`]), never
/// a corrupt file.
fn check_channels(path: &Path, channels: u16) -> Result<(), AssetError> {
    if channels == 1 || channels == 2 {
        Ok(())
    } else {
        Err(AssetError::unsupported_feature(
            path,
            format!("{channels}-channel audio: only mono and stereo are supported"),
        ))
    }
}

/// Validates a WAV sample format and returns its full-scale divisor.
///
/// Accepts 8/16/24/32-bit integer PCM and 32-bit float; anything else
/// (12-bit oddities, 64-bit float, integer widths past 32) is a
/// loader-narrowness failure ([`AssetError::UnsupportedFeature`]), not
/// a corrupt file. The returned `f64` divisor is exact for every
/// accepted width (all are powers of two), so the normalization in
/// [`normalize_int_sample`] divides by the true full scale.
fn check_wav_sample_format(path: &Path, spec: &hound::WavSpec) -> Result<f64, AssetError> {
    match (spec.sample_format, spec.bits_per_sample) {
        (hound::SampleFormat::Int, 8)
        | (hound::SampleFormat::Int, 16)
        | (hound::SampleFormat::Int, 24)
        | (hound::SampleFormat::Int, 32) => {
            // Powers of two: exactly representable in `f64`.
            Ok(f64::from(1u32 << (spec.bits_per_sample - 1)))
        }
        (hound::SampleFormat::Float, 32) => Ok(1.0),
        (format, bits) => Err(AssetError::unsupported_feature(
            path,
            format!("WAV {format:?} samples at {bits} bits per sample"),
        )),
    }
}

/// Normalizes one integer PCM sample into `[-1, 1]`.
///
/// `full_scale` is the divisor from [`check_wav_sample_format`]
/// (128 for 8-bit through 2147483648 for 32-bit): most-negative maps
/// to exactly -1.0, most-positive to just under 1.0 — the standard
/// two's-complement PCM mapping, applied once at the boundary so no
/// consumer repeats it.
fn normalize_int_sample(value: i32, full_scale: f64) -> f32 {
    // One narrowing float conversion for the whole loader: the quotient
    // is in [-1, 1] and `f32` holds it with room to spare, so this is a
    // value conversion with a known range, not an `as` cast dodging a
    // type error. (`f64` carries the division because no `From<i32>`
    // exists for `f32` — going straight to `f32` would round twice.)
    (f64::from(value) / full_scale) as f32
}

/// Refuses a decode whose sample count exceeds `max_decode_samples`.
///
/// Shared by the WAV header pre-check (claimed count, refused before
/// any sample allocation) and the Vorbis running-total gate (actual
/// count, refused the moment it passes): both report
/// [`AssetError::OverBudget`] with the same numbers. One function so
/// the two gates cannot drift into different taxonomies for the same
/// condition.
fn check_samples_budget(
    path: &Path,
    max_decode_samples: u64,
    claimed: u64,
) -> Result<(), AssetError> {
    if claimed > max_decode_samples {
        return Err(AssetError::over_budget(path, max_decode_samples, claimed));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// Checked-in fixture path (see `mesh.rs` tests for why
    /// `CARGO_MANIFEST_DIR` instead of a relative path).
    fn fixture(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures")
            .join(name)
    }

    /// Scratch file for runtime-built inputs, unique per test name so
    /// parallel tests never share a path.
    fn write_temp(name: &str, bytes: &[u8]) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("canary-assets-sound-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("scratch dir must be creatable");
        let path = dir.join(name);
        std::fs::write(&path, bytes).expect("scratch fixture must be writable");
        path
    }

    /// Writes a WAV file in-memory with `hound`'s own writer so the
    /// bit-depth/channel arms are exercised without one checked-in
    /// fixture per combination. Deterministic: fixed spec, no chunks
    /// beyond `fmt ` and `data`, so identical input yields identical
    /// bytes.
    fn encode_wav_int(
        channels: u16,
        sample_rate: u32,
        bits_per_sample: u16,
        samples: &[i32],
    ) -> Vec<u8> {
        let mut out = Vec::new();
        let spec = hound::WavSpec {
            channels,
            sample_rate,
            bits_per_sample,
            sample_format: hound::SampleFormat::Int,
        };
        let mut writer = hound::WavWriter::new(Cursor::new(&mut out), spec)
            .expect("in-memory WAV encode must succeed");
        for sample in samples {
            writer
                .write_sample(*sample)
                .expect("in-memory WAV sample write must succeed");
        }
        writer
            .finalize()
            .expect("in-memory WAV finalize must succeed");
        out
    }

    /// Writes a 32-bit float WAV in-memory (see [`encode_wav_int`] for
    /// why the writer is reused here instead of a fixture).
    fn encode_wav_float(channels: u16, sample_rate: u32, samples: &[f32]) -> Vec<u8> {
        let mut out = Vec::new();
        let spec = hound::WavSpec {
            channels,
            sample_rate,
            bits_per_sample: 32,
            sample_format: hound::SampleFormat::Float,
        };
        let mut writer = hound::WavWriter::new(Cursor::new(&mut out), spec)
            .expect("in-memory WAV encode must succeed");
        for sample in samples {
            writer
                .write_sample(*sample)
                .expect("in-memory WAV sample write must succeed");
        }
        writer
            .finalize()
            .expect("in-memory WAV finalize must succeed");
        out
    }

    /// Exact float comparison via bit patterns: lossless WAV outputs
    /// round-trip the file's sample bytes with one exact division in
    /// between, so bitwise equality against hand-computed values is the
    /// honest assertion (and it sidesteps epsilon debates entirely).
    fn assert_f32_bits_eq(actual: &[f32], expected: &[f32]) {
        assert_eq!(
            actual.len(),
            expected.len(),
            "length mismatch: {} vs {}",
            actual.len(),
            expected.len()
        );
        for (index, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
            assert_eq!(
                a.to_bits(),
                e.to_bits(),
                "sample mismatch at index {index}: {a} vs {e}"
            );
        }
    }

    #[test]
    fn mono_wav_fixture_loads_with_known_rate_channels_and_samples() {
        let sound = load_sound(&fixture("tone-mono-8k.wav")).expect("mono WAV fixture must load");
        assert_eq!(sound.sample_rate(), 8000);
        assert_eq!(sound.channel_count(), 1);
        assert_eq!(sound.frame_count(), 8);
        // Hand-picked 16-bit values from the fixtures README, divided
        // by the 16-bit full scale (32768): all but one are exactly
        // representable, and 32767/32768 needs only 15 mantissa bits,
        // so every expectation below is bit-exact.
        assert_f32_bits_eq(
            sound.samples(),
            &[0.0, 0.25, 0.5, 0.75, 0.999_969_5, -1.0, -0.5, 0.0],
        );
    }

    #[test]
    fn stereo_ogg_fixture_loads_with_known_rate_channels_and_tone_shape() {
        let sound =
            load_sound(&fixture("tone-stereo-8k.ogg")).expect("stereo Ogg fixture must load");
        assert_eq!(sound.sample_rate(), 8000);
        assert_eq!(sound.channel_count(), 2);
        assert!(
            sound.frame_count() > 0,
            "Vorbis encode trims/pads framing, so the count is asserted nonzero, not exact"
        );
        assert_eq!(
            sound.samples().len(),
            sound.frame_count() * 2,
            "samples must hold whole stereo frames"
        );
        for (index, sample) in sound.samples().iter().enumerate() {
            assert!(
                sample.is_finite(),
                "decoded sample {index} must be finite, got {sample}"
            );
            assert!(
                (-1.0..=1.0).contains(sample),
                "decoded sample {index} must stay in [-1, 1], got {sample}"
            );
        }
        // The source is a 440 Hz sine at 0.5 amplitude starting at phase
        // 0 (see the fixtures README): the opening frame sits near the
        // zero crossing, and the peak frame in the first period nears
        // 0.5. Vorbis is lossy, so both windows are generous — they pin
        // the tone's shape, not the encoder's exact quantization.
        let left_first = sound.samples()[0];
        assert!(
            left_first.abs() < 0.15,
            "opening left sample must sit near the sine zero crossing, got {left_first}"
        );
        let first_period_peak = sound
            .samples()
            .chunks_exact(2)
            .take(18)
            .map(|frame| frame[0].abs())
            .fold(0.0f32, f32::max);
        assert!(
            (0.3..=0.7).contains(&first_period_peak),
            "first-period peak must near the 0.5 source amplitude, got {first_period_peak}"
        );
    }

    #[test]
    fn stereo_wav_decodes_to_interleaved_frames() {
        // Left ramps up, right ramps down: interleaving bugs transpose
        // these, so distinct per-channel values catch them.
        let bytes = encode_wav_int(2, 22050, 16, &[0, 0, 16384, -16384, 32767, -32768]);
        let path = write_temp("stereo.wav", &bytes);
        let sound = load_sound(&path).expect("stereo WAV must load");
        assert_eq!(sound.sample_rate(), 22050);
        assert_eq!(sound.channel_count(), 2);
        assert_eq!(sound.frame_count(), 3);
        assert_f32_bits_eq(sound.samples(), &[0.0, 0.0, 0.5, -0.5, 0.999_969_5, -1.0]);
    }

    #[test]
    fn eight_bit_wav_divides_by_128() {
        // 8-bit PCM is unsigned on disk; `hound` abstracts that away
        // and yields signed values, so the loader divides by 128 over
        // the signed range.
        let bytes = encode_wav_int(1, 8000, 8, &[-128, -64, 0, 64, 127]);
        let path = write_temp("eight-bit.wav", &bytes);
        let sound = load_sound(&path).expect("8-bit WAV must load");
        assert_f32_bits_eq(sound.samples(), &[-1.0, -0.5, 0.0, 0.5, 0.992_187_5]);
    }

    #[test]
    fn twenty_four_bit_wav_divides_by_full_scale() {
        // 2^23 is out of range for signed 24-bit (max 2^23 - 1), so the
        // top of the range is pinned with the largest encodable value;
        // 8388607/8388608 needs only 24 significant bits, so bit-exact
        // (spelled with 7 digits: the 8-digit spelling denotes the same
        // `f32` but trips `excessive_precision`).
        let bytes = encode_wav_int(1, 48000, 24, &[0, 8_388_607, -8_388_608]);
        let path = write_temp("twenty-four-bit.wav", &bytes);
        let sound = load_sound(&path).expect("24-bit WAV must load");
        assert_eq!(sound.sample_rate(), 48000);
        assert_f32_bits_eq(sound.samples(), &[0.0, 0.999_999_9, -1.0]);
    }

    #[test]
    fn thirty_two_bit_int_wav_divides_by_full_scale() {
        let bytes = encode_wav_int(1, 44100, 32, &[0, 2_147_483_647, -2_147_483_648]);
        let path = write_temp("thirty-two-bit.wav", &bytes);
        let sound = load_sound(&path).expect("32-bit WAV must load");
        assert_eq!(sound.sample_rate(), 44100);
        assert_f32_bits_eq(sound.samples(), &[0.0, 1.0, -1.0]);
    }

    #[test]
    fn thirty_two_bit_float_wav_passes_through() {
        let bytes = encode_wav_float(1, 44100, &[0.0, -0.25, 0.5, 1.0]);
        let path = write_temp("float.wav", &bytes);
        let sound = load_sound(&path).expect("float WAV must load");
        assert_f32_bits_eq(sound.samples(), &[0.0, -0.25, 0.5, 1.0]);
    }

    #[test]
    fn missing_file_is_io_not_a_panic() {
        let err = load_sound(Path::new("definitely-not-a-sound.wav"))
            .expect_err("missing file must fail");
        assert!(
            matches!(err, AssetError::Io { .. }),
            "missing file must be Io, got: {err:?}"
        );
    }

    #[test]
    fn within_root_loads_valid_files_value_identical_and_refuses_escapes() {
        let dir = tempfile::tempdir().expect("failed to create temp dir");
        let root = dir.path().join("assets");
        std::fs::create_dir(&root).expect("root must be creatable");
        let bytes = std::fs::read(fixture("tone-mono-8k.wav")).expect("WAV fixture must exist");
        std::fs::write(root.join("tone-mono-8k.wav"), &bytes)
            .expect("rooted copy must be writable");
        // The `..` escape needs a real file outside the root: a
        // dangling traversal fails as Io (missing file), which would
        // prove nothing about confinement.
        std::fs::write(dir.path().join("tone-mono-8k.wav"), &bytes)
            .expect("outside copy must be writable");

        let direct = load_sound(&root.join("tone-mono-8k.wav")).expect("rooted copy must load");
        let confined = load_sound_within_root(&root, Path::new("tone-mono-8k.wav"))
            .expect("in-root candidate must load");
        assert_eq!(
            confined, direct,
            "confinement must change which paths are accepted, never the values"
        );

        for escape in [
            Path::new("../tone-mono-8k.wav").to_path_buf(),
            dir.path().join("tone-mono-8k.wav"),
        ] {
            let err = load_sound_within_root(&root, &escape)
                .expect_err("escape must fail before decoding");
            assert!(
                matches!(err, AssetError::OutsideRoot { .. }),
                "escape must be OutsideRoot, got: {err:?}"
            );
        }
    }

    #[test]
    fn oversized_file_is_refused_before_allocating() {
        use crate::io::MAX_ASSET_FILE_BYTES;

        // A sparse file reports past the file budget from metadata
        // while costing (almost) nothing on disk: the loader must
        // refuse it without allocating its contents, before any
        // decode budget is even reached.
        let dir = tempfile::tempdir().expect("failed to create temp dir");
        let path = dir.path().join("big.wav");
        let file = std::fs::File::create(&path).expect("sparse fixture must be creatable");
        file.set_len(MAX_ASSET_FILE_BYTES + 1)
            .expect("sparse resize must succeed");
        drop(file);

        let err = load_sound(&path).expect_err("over-limit file must fail");
        match &err {
            AssetError::OverBudget { limit, actual, .. } => {
                assert_eq!(*limit, MAX_ASSET_FILE_BYTES);
                assert_eq!(*actual, MAX_ASSET_FILE_BYTES + 1);
            }
            other => panic!("over-limit file must be OverBudget, got: {other:?}"),
        }
        assert_eq!(
            err.path(),
            Some(path.as_path()),
            "the error must name the offending file"
        );
    }

    #[test]
    fn garbage_bytes_are_invalid_format() {
        let path = write_temp("garbage.wav", b"this is not a sound file at all!!");
        let err = load_sound(&path).expect_err("garbage must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "garbage must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn too_short_files_are_invalid_format() {
        let path = write_temp("tiny.wav", b"OggS");
        let err = load_sound(&path).expect_err("4-byte file must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "sub-header file must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn wrong_magic_png_bytes_are_invalid_format() {
        // Right loader family (bytes on disk), wrong container: the PNG
        // fixture's magic matches neither WAV nor Ogg dispatch.
        let bytes =
            std::fs::read(fixture("rgba2x2.png")).expect("PNG fixture must exist for magic test");
        let path = write_temp("misnamed.wav", &bytes);
        let err = load_sound(&path).expect_err("PNG bytes must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "wrong magic must be InvalidFormat, got: {err:?}"
        );
        assert!(
            err.to_string().contains("magic"),
            "message must name the magic dispatch, got: {err}"
        );
    }

    #[test]
    fn wrong_magic_glb_bytes_are_invalid_format() {
        let bytes =
            std::fs::read(fixture("quad.glb")).expect("GLB fixture must exist for magic test");
        let path = write_temp("misnamed2.ogg", &bytes);
        let err = load_sound(&path).expect_err("GLB bytes must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "wrong magic must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn truncated_wav_fixture_is_invalid_format() {
        let full = std::fs::read(fixture("tone-mono-8k.wav")).expect("WAV fixture must exist");
        let path = write_temp("truncated.wav", &full[..full.len() / 2]);
        let err = load_sound(&path).expect_err("truncated file must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "truncated file must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn truncated_ogg_fixture_is_invalid_format() {
        let full = std::fs::read(fixture("tone-stereo-8k.ogg")).expect("Ogg fixture must exist");
        let path = write_temp("truncated.ogg", &full[..full.len() * 3 / 4]);
        let err = load_sound(&path).expect_err("truncated Ogg must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "truncated Ogg must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn ogg_magic_with_garbage_payload_is_invalid_format() {
        // The magic dispatches to Ogg, but the headers never parse.
        let mut bytes = vec![0u8; 64];
        bytes[0..4].copy_from_slice(b"OggS");
        let path = write_temp("bogus.ogg", &bytes);
        let err = load_sound(&path).expect_err("bogus Ogg must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "bogus Ogg must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn riff_without_wave_is_invalid_format() {
        // `RIFF....` but not `WAVE`: not routed to either decoder.
        let mut bytes = vec![0u8; 32];
        bytes[0..4].copy_from_slice(b"RIFF");
        bytes[8..12].copy_from_slice(b"AVIX");
        let path = write_temp("riff-avi.wav", &bytes);
        let err = load_sound(&path).expect_err("RIFF/AVI must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "non-WAVE RIFF must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn tiny_budget_refuses_before_decoding() {
        // The mono fixture holds exactly 8 sample values; a ceiling of
        // 7 must fail with both numbers attached, not decode anyway.
        let err = load_sound_with_budget(&fixture("tone-mono-8k.wav"), 7)
            .expect_err("7-sample budget must fail an 8-sample sound");
        match err {
            AssetError::OverBudget { limit, actual, .. } => {
                assert_eq!(limit, 7);
                assert_eq!(actual, 8);
            }
            other => panic!("must be OverBudget, got: {other:?}"),
        }
    }

    #[test]
    fn exact_budget_is_enough() {
        let sound = load_sound_with_budget(&fixture("tone-mono-8k.wav"), 8)
            .expect("a budget of exactly the sample count must succeed");
        assert_eq!(sound.samples().len(), 8);
    }

    #[test]
    fn zero_budget_refuses_even_the_smallest_fixture() {
        let err = load_sound_with_budget(&fixture("tone-mono-8k.wav"), 0)
            .expect_err("a zero budget must refuse everything");
        match err {
            AssetError::OverBudget { limit, actual, .. } => {
                assert_eq!(limit, 0);
                assert_eq!(actual, 8, "the mono fixture holds exactly 8 samples");
            }
            other => panic!("zero budget must be OverBudget, got: {other:?}"),
        }
    }

    #[test]
    fn tiny_budget_refuses_ogg_mid_stream() {
        // Vorbis carries no upfront total, so the running-total gate
        // must fire mid-decode: a 2-sample ceiling on a hundreds-long
        // stream fails OverBudget, never InvalidFormat.
        let err = load_sound_with_budget(&fixture("tone-stereo-8k.ogg"), 2)
            .expect_err("2-sample budget must fail the Ogg fixture");
        assert!(
            matches!(err, AssetError::OverBudget { .. }),
            "mid-stream budget breach must be OverBudget, got: {err:?}"
        );
    }

    #[test]
    fn lying_wav_header_claiming_gigasamples_is_over_budget() {
        // A valid 8-sample fixture whose data-chunk size is patched to
        // claim gigabytes of samples: the header pre-check must refuse it
        // without attempting the allocation. The patched size stays a
        // multiple of the 16-bit mono frame size — hound itself rejects
        // ragged data chunks at parse time, before the loader's budget
        // gate ever runs — so the lie reaches the gate it is meant to
        // test. The data-chunk size lives 4 bytes past the `data` tag;
        // the tag offset is found by scanning rather than hardcoded, so
        // writer layout drift fails loudly (panic in test setup) instead
        // of patching the wrong bytes silently.
        let mut bytes = std::fs::read(fixture("tone-mono-8k.wav")).expect("WAV fixture must exist");
        let tag = bytes
            .windows(4)
            .position(|window| window == b"data")
            .expect("WAV fixture must hold a data chunk");
        bytes[tag + 4..tag + 8].copy_from_slice(&(u32::MAX - 1).to_le_bytes());
        let path = write_temp("lying-header.wav", &bytes);
        let err = load_sound(&path).expect_err("gigasample claim must fail");
        match err {
            AssetError::OverBudget { limit, actual, .. } => {
                assert_eq!(limit, DEFAULT_MAX_SOUND_SAMPLES);
                assert!(
                    actual > DEFAULT_MAX_SOUND_SAMPLES,
                    "patched claim must dwarf the budget, got {actual}"
                );
            }
            other => panic!("lying header must be OverBudget, got: {other:?}"),
        }
    }

    #[test]
    fn four_channel_wav_is_unsupported_not_misrendered() {
        // Four channels of silence: well-formed, but this minimal
        // loader has no surround policy — declined, never downmixed.
        let bytes = encode_wav_int(4, 8000, 16, &[0; 16]);
        let path = write_temp("quad.wav", &bytes);
        let err = load_sound(&path).expect_err("4-channel WAV must fail");
        assert!(
            matches!(err, AssetError::UnsupportedFeature { .. }),
            "multichannel must be UnsupportedFeature, got: {err:?}"
        );
    }

    #[test]
    fn unsupported_sample_formats_are_declined_before_any_sample_is_read() {
        // The format gate is unit-tested directly (not through a file)
        // on purpose: hound itself refuses several odd headers at parse
        // time (12-bit depth, 64-bit integer width), so those shapes
        // never reach this gate in this hound version. The gate's own
        // contract — anything outside 8/16/24/32-bit integer and 32-bit
        // float is loader narrowness, not file corruption — is pinned
        // here against synthetic specs instead.
        for (format, bits) in [
            (hound::SampleFormat::Int, 12),
            (hound::SampleFormat::Int, 64),
            (hound::SampleFormat::Float, 64),
        ] {
            let spec = hound::WavSpec {
                channels: 1,
                sample_rate: 8000,
                bits_per_sample: bits,
                sample_format: format,
            };
            let err = check_wav_sample_format(Path::new("synthetic.wav"), &spec)
                .expect_err("narrow loader must decline this width");
            assert!(
                matches!(err, AssetError::UnsupportedFeature { .. }),
                "excess/odd width must be UnsupportedFeature, got: {err:?}"
            );
        }
    }

    #[test]
    fn twelve_bit_wav_fails_at_parse_before_the_loader_gate() {
        // A 16-bit fixture with its fmt-chunk depth patched to 12: hound
        // itself rejects non-multiple-of-8 depths at parse time, so this
        // surfaces as InvalidFormat (unparseable file), never reaching
        // the loader's UnsupportedFeature gate above. Pinned here so a
        // hound upgrade that starts parsing 12-bit changes this test
        // loudly instead of silently reclassifying the file.
        // `bits_per_sample` sits at byte offset 34 in a canonical
        // 16-byte fmt chunk (verified against the writer's output
        // below); anything else means the writer layout moved and the
        // test must fail loudly rather than patch blindly.
        let mut bytes = std::fs::read(fixture("tone-mono-8k.wav")).expect("WAV fixture must exist");
        assert_eq!(
            u16::from_le_bytes([bytes[34], bytes[35]]),
            16,
            "offset 34 must hold the 16-bit depth the fixture was generated with"
        );
        bytes[34..36].copy_from_slice(&12u16.to_le_bytes());
        let path = write_temp("twelve-bit.wav", &bytes);
        let err = load_sound(&path).expect_err("12-bit WAV must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "hound-unparseable depth must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn empty_wav_is_invalid_format() {
        // Header-only file: zero frames is a content failure (there is
        // nothing to play), not a budget or narrowness one.
        let bytes = encode_wav_int(1, 8000, 16, &[]);
        let path = write_temp("empty.wav", &bytes);
        let err = load_sound(&path).expect_err("empty WAV must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "empty stream must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn loaded_sound_flows_through_asset_store_with_stable_identity() {
        use crate::{AssetId, AssetStore, LOADER_VERSION};

        let path = fixture("tone-mono-8k.wav");
        let bytes = std::fs::read(&path).expect("WAV fixture must exist");
        // Identity and values come from the same file bytes: the hash
        // mixes in LOADER_VERSION (proved in `id.rs` tests), so a loader
        // fix deterministically changes IDs without the loader itself
        // hashing anything.
        assert_eq!(
            AssetId::for_file(&path).expect("readable fixture must hash"),
            AssetId::new(&bytes),
            "file identity must equal the in-memory hash of the same bytes"
        );
        assert_eq!(
            AssetId::new(&bytes),
            AssetId::with_version(&bytes, LOADER_VERSION),
            "`new` must hash under LOADER_VERSION"
        );

        let sound = load_sound(&path).expect("WAV fixture must load");
        let mut store = AssetStore::new();
        let handle = store.insert(sound);
        let stored = store.get(handle).expect("live handle must resolve");
        assert_eq!(stored.frame_count(), 8);
        assert_eq!(stored.sample_rate(), 8000);
    }

    #[test]
    fn git_lfs_pointer_bytes_are_invalid_format_not_a_panic() {
        // Given: what a fixture resolves to when Git LFS objects were not
        // fetched (CI without `lfs: true`): pointer text, not audio.
        let pointer =
            b"version https://git-lfs.github.com/spec/v1\noid sha256:0000000000000000000000000000000000000000000000000000000000000000\nsize 12345\n";
        let path = write_temp("lfs-pointer.wav", pointer);

        // When: loaded. Then: Err (InvalidFormat), never a panic.
        let err = load_sound(&path).expect_err("LFS pointer text must fail");
        assert!(
            matches!(err, AssetError::InvalidFormat { .. }),
            "LFS pointer bytes must be InvalidFormat, got: {err:?}"
        );
    }

    #[test]
    fn missing_parent_directory_is_io_not_a_panic() {
        // Given: a path under a directory that does not exist at all.
        let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/does-not-exist-dir/tone-mono-8k.wav");

        // When: loaded. Then: Io (the read fails before any decode).
        let err = load_sound(&path).expect_err("missing directory must fail");
        assert!(
            matches!(err, AssetError::Io { .. }),
            "missing parent directory must be Io, got: {err:?}"
        );
    }

    #[test]
    fn unreadable_file_reports_io_even_under_zero_budget() {
        // Given: a path that cannot be read at all, with a budget of zero.
        // Then: Io, not OverBudget — the read runs before every budget
        // guard, so a missing file can never report a budget failure.
        let err = load_sound_with_budget(Path::new("definitely-not-a-sound.wav"), 0)
            .expect_err("missing file must fail");
        assert!(
            matches!(err, AssetError::Io { .. }),
            "read-before-budget: missing file must be Io even with budget 0, got: {err:?}"
        );
    }
}
